@startuml
abstract class Altura{
    -capacidad: int
    +abstract crearLugares
}

class AlturaNumerada{}
class AlturaSinNumerar{}

class Asiento{
    -numeroAsiento
    -estaOcupado
}

abstract class Sector{
    -nombre
    +abstract reservarLugar()
}

class Belgrano{}
class SanMartin{}
class Sivori{}
class Centenario{}

class Partido {
    -fecha: Date
}

Altura <|-- AlturaNumerada
Altura <|-- AlturaSinNumerar

Altura *-- Sector
AlturaNumerada *-- Asiento

Sector <|-- Belgrano
Sector <|-- SanMartin
Sector <|-- Sivori
Sector <|-- Centenario

Partido *-- Sector

@enduml