@startuml
abstract class Altura{
    #capacidad: int
    -precio: double
    +abstract reservarLugares(): boolean
}

class AlturaNumerada{}
class AlturaSinNumerar{}

class Asiento{
    -numeroAsiento
    -estaOcupado
    +ocupar()
    +liberar()
}

abstract class Sector{
    -nombre
    +abstract reservarLugar()
}

class Belgrano{}
class SanMartin{}
class Sivori{}
class Centenario{}

class Estadio {
    +reservarSector(nombreSector: String, altura: String, numeroAsiento: int): void
}

class Partido{
    -equipoLocal: String
    -equipoVisitante: String
    -Fecha: Date
    -precioBase: double
}

class Entrada{
    -id: int
    -numeroAsiento: Integer
    -precio: double
    -fecha: Date

}

enum EstadoEntrada {
    ACTIVA
    CANCELADA
}

Altura <|-- AlturaNumerada
Altura <|-- AlturaSinNumerar

Altura --* Sector
AlturaNumerada *-- Asiento

Sector <|-- Belgrano
Sector <|-- SanMartin
Sector <|-- Sivori
Sector <|-- Centenario

Estadio *-- Sector

Entrada *--o Partido
Entrada o-- Sector
Entrada o-- Altura
Entrada --> EstadoEntrada

Partido *-- Estadio

@enduml